//
//
// Name: Emily Puth
// ID: 28239807
//
//

#ifndef ROOF_AND_FENCE_CONSTANTS_HPP_
#define ROOF_AND_FENCE_CONSTANTS_HPP_


enum Price
{
	WOODEN_FENCE_PRICE = 300,
	CHAIN_LINK_FENCE_PRICE = 180,
	TILE_ROOF_PRICE = 250,
	SHINGLE_ROOF_PRICE = 125,
	METAL_ROOF_PRICE = 100
};

enum LengthOrCover
{
	WOODEN_FENCE_LENGTH = 50,
	CHAIN_LINK_FENCE_LENGTH = 50,
	TILE_ROOF_COVER = 75,
	SHINGLE_ROOF_COVER = 100,
	METAL_ROOF_COVER = 125
};

enum Order
{
	WOODEN_FENCE = 1,
	CHAIN_LINK_FENCE = 2,
	TILE_ROOF = 3,
	SHINGLE_ROOF = 4,
	METAL_ROOF = 5,
	QUIT_AND_DISPLAY = 6
};


#endif /* ROOF_AND_FENCE_CONSTANTS_HPP_ */
